version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: scripts/kill_container.sh
      timeout: 30
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 600
      runas: ec2-user
